# Generated by Django 6.0.8 on 2026-08-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(verbose_name='Start date')),
                ('enddate', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Password')),
            ],
        ),
    ]
