# Generated by Django 6.0.8 on 2026-08-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile657', '0002_lock_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RenameModel('Lock', 'Key'),
    ]
