# Generated by Django 6.0.8 on 2026-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile657', '0005_passworddelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='invites',
            field=models.PositiveIntegerField(blank=True, help_text='Number of invites. Leave empty for unlimitet.', null=True),
        ),
    ]
